apiVersion: v1
kind: Secret
metadata:
  name: com.hammerspace.csi.credentials
  namespace: kube-system
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
stringData:
  endpoint: "https://anvil.example.com"
