application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  deployerImage:
    type: string
    x-google-marketplace:
      type: DEPLOYER_IMAGE
  imageHammerspaceCsi:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: imageHammerspaceCsiRepo
            after: imageHammerspaceCsiTag
  serviceAcc:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
            - apiGroups: [""]
              resources: ["nodes"]
              verbs: ["get", "list", "update"]
            - apiGroups: [""]
              resources: ["namespaces"]
              verbs: ["get", "list"]
            - apiGroups: [""]
              resources: ["persistentvolumes"]
              verbs: ["get", "list", "watch", "create", "delete", "update"]
            - apiGroups: [""]
              resources: ["persistentvolumeclaims"]
              verbs: ["get", "list", "watch", "update"]
            - apiGroups: ["storage.k8s.io"]
              resources: ["storageclasses"]
              verbs: ["get", "list", "watch"]
            - apiGroups: [""]
              resources: ["events"]
              verbs: ["list", "watch", "create", "update", "patch"]
            - apiGroups: [""]
              resources: ["endpoints"]
              verbs: ["list", "watch", "create", "update", "delete", "get"]
            - apiGroups: [""]
              resources: ["secrets"]
              verbs: ["get", "list"]
            - apiGroups: ["snapshot.storage.k8s.io"]
              resources: ["volumesnapshotclasses"]
              verbs: ["get", "list", "watch"]
            - apiGroups: ["snapshot.storage.k8s.io"]
              resources: ["volumesnapshotcontents"]
              verbs: ["create", "get", "list", "watch", "update", "delete"]
            - apiGroups: ["snapshot.storage.k8s.io"]
              resources: ["volumesnapshots"]
              verbs: ["get", "list", "watch", "update"]
            - apiGroups: ["apiextensions.k8s.io"]
              resources: ["customresourcedefinitions"]
              verbs: ["create", "list", "watch", "delete"]
            - apiGroups: ["storage.k8s.io"]
              resources: ["volumeattachments"]
              verbs: ["get", "list", "watch", "update"]
            - apiGroups: ["storage.k8s.io"]
              resources: ["storageclasses"]
              verbs: ["get", "list", "watch", "update"]
  hsClusterIp:
    type: string
    title: Hammerspace Anvil Internal IP
    description: Internal IP of deployed Hammerspace Anvil
    placeholder: '192.169.0.2'
  hsAdminUser:
    type: string
    title: Hammerspace Anvil Administrator Username
    description: User with administrator privelages of deployed Hammerspace Anvil
    default: admin
  hsPassword:
    type: string
    title: Hammerspace Anvil Admin Password
    description: Administrator password of deployed Hammerspace Anvil
required:
- name
- namespace
- deployerImage
- imageHammerspaceCsi
- serviceAcc
- hsClusterIp
- hsAdminUser
- hsPassword
