kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hs-storage
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: com.hammerspace.csi
mountOptions:
  - "timeo=100"
parameters:
  # Optional, for use if we are supporting BlockVolumes. Auto-created if it does not exist. Never delete by the driver
  blockBackingShareName: k8s-block-storage
  # Objectives to set on shares in addition to HS cluster defaults
  objectives: "place-on-all,optimize-for-capacity"
  # ';' seperated list of <subnet>,access,rootSquash
  exportOptions: "*,RW,false; 172.168.0.0/20,RO,true"
  # One should be careful to set this if shares are used outside of the cluster. -1 means do not delete the shares at all
  deleteDelay: "0"
  # The name format of provisioned volumes, %s is replaced with pvc-<uuid>
  volumeNameFormat: "csi-%s"
  # Comma-separated list of additional metadata to put on volumes
  additionalVolumeExtendedInfo: "storageClass=hs-storage"